// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp00O4DX_1vvNApMJmpKpOgntjIWA2L6A',
    appId: '1:322730580665:web:13aa366e735a83c0541968',
    messagingSenderId: '322730580665',
    projectId: 'beda-54797',
    authDomain: 'beda-54797.firebaseapp.com',
    storageBucket: 'beda-54797.appspot.com',
    measurementId: 'G-B1N8PPJTL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBUhMlFFJU1vQMRhCT9PwpJ3cqNULRS8',
    appId: '1:322730580665:android:809202ffb20dda8a541968',
    messagingSenderId: '322730580665',
    projectId: 'beda-54797',
    storageBucket: 'beda-54797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2L2fkuShiufM70nC3czGFI4Yjw4Z8QQk',
    appId: '1:322730580665:ios:ecb810a76fc68982541968',
    messagingSenderId: '322730580665',
    projectId: 'beda-54797',
    storageBucket: 'beda-54797.appspot.com',
    iosClientId: '322730580665-mbjgks320da0eea92tk125a3o2fde9fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.beda2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2L2fkuShiufM70nC3czGFI4Yjw4Z8QQk',
    appId: '1:322730580665:ios:0b4dd0d369e8e355541968',
    messagingSenderId: '322730580665',
    projectId: 'beda-54797',
    storageBucket: 'beda-54797.appspot.com',
    iosClientId: '322730580665-4eneqiiskh9ms8h3r2654qij8pkalmo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.beda2.RunnerTests',
  );
}
